hack: always build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,6 +13,8 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    env:
+      SHOULD_BUILD: true
 
     steps:
       - uses: actions/checkout@v4
@@ -23,15 +25,15 @@ jobs:
       - name: Get latest upstream tag
         run: echo "LATEST_UPSTREAM_TAG=$(./get_latest_upstream_tag.sh)" >> $GITHUB_ENV
 
-      - name: Check if we should build
-        run: |
-          set +e # Allow commands to fail
-          ./should_build.sh
-          if [ $? -eq 0 ]; then
-            echo "SHOULD_BUILD=true" >> $GITHUB_ENV
-          else
-            echo "SHOULD_BUILD=false" >> $GITHUB_ENV
-          fi
+      # - name: Check if we should build
+      #   run: |
+      #     set +e # Allow commands to fail
+      #     ./should_build.sh
+      #     if [ $? -eq 0 ]; then
+      #       echo "SHOULD_BUILD=true" >> $GITHUB_ENV
+      #     else
+      #       echo "SHOULD_BUILD=false" >> $GITHUB_ENV
+      #     fi
 
       - name: Install Dependencies
         if: ${{ env.SHOULD_BUILD == 'true' }}
